language: python

python:
  - '2.7'

install: pip install -r requirements.txt

script: echo "OK"

deploy:
  provider: pypi
  user: gszathmari
  password:
    secure: Oftd8v68q/eVb3gKEN/QILz1ZwLf0USscMLdUyeiKDk5Plzh5liRwt6Ik7hzJEimaf4X4RyMEvhhRkdl/KBS6s5n8vy4gGemq6+u7OmgK6bFP8P4V2L1MFY07d6fKEfUJfL8j5GR6+m+uSLqv3PTQ4Jt2vNtq534Bv2j4BysM8DN/y1fhYBQ8eS54hMehlvCCURj+gRlG9V2gtxOG6Zy6CTn5TibesLMN8HuN6W3NGcrNSx2VtSk12n4i7RCIE6JD4czezX5v27iAB+u/hSVCGcI9g3MuDXTgO6fgc0ocBuuCFVu3fBapcOW4qLedU5OOxMDQks0FlGlIEU0XP9+vnmCksmoXnHgdlypyLq320MHNYhxA0QLGL2E/RQf6vBWpJpT0Mh4c+5d2sLsbfm/LrKNtYcQua2V4TQmUxhs9weVWYhF/sYnVn0q6CalntQ4VZMSH6GvH4JEQU5bXBwZ5djOuaDhYsjq5pds6YFBpqxQHw4zYB1x6MoaeCKZgLuSfPdmnQ32ru1/TEadPSuUeDuu73HDtn6smZmAuX2H614AiRVw8EiIQ5UNPR7HK2/sH94boo8bnKfC7gv+CTZmSf9uOo6MeCH9/nMEkEpkmlyN63huhd86bJSPTvQiacBB2RYK4JSOD+tMeRdoGvv/I+ArVvHY8HEZc4MFNEz7IP8=
  distributions: sdist bdist_wheel
  on:
    tags: true
